SELECT NO, NAME, TDATE FROM TRIP ORDER BY NO;
SELECT NAME FROM TRIP WHERE TCODE = 101 OR TCODE = 103;
SELECT NO AND NAME FROM TRIP WHERE '2015-02-10' < TDATE < '2015-04-01';
SELECT NO, NAME, TDATE, KM, TCODE FROM TRIP WHERE KM >100 ORDER BY NOP;
SELECT COUNT (*), TCODE From TRIP GROUP BY TCODE HAVNING COUnT (*) > 1;
SELECT DISTINCT TCODE from TRIP;
SELECT A.TCODE, NAME, TTYPE FROM TRIP A, TRANSPORT B WHERE A. TCODE = B. TCODE AND KM < 90;
SELECT NAME, KM *PERKM FROM TRIP A, TRANSPORT B WHERE A. TCODE = B. TCODE AND A. TCODE = 105;

/*
5. TO DISPLAY THE MORE THAN ONE COUNT OF TCODE FROM THE TABLE TRIP
6. TO DISPALY SEPERATE TCODE OF TABLE TRIP
7. TO DISPAY THE NAME AND CODE OF THOSE TRANS PORTERS, WHO HAVE TRAVELLED MORE THAN 90 KMS.
8. TO DISPLAY THE NAME AND EXPENDITARE OF A TRANSPORTER WHO HAVE TCODE AS 105.
 */


/*

*/